### ISSUE TITLE
question for "Table8: Standard configuration" about "Holding cost"

### ISSUE THREAD

**Issue by BackMountainDevil** [VictorYXL/ReplenishmentEnv#27]
In table8 of related paper, the value of  "Holding cost" is "0.002 + 0.001",  why not just write it to 0.003?

In file "sku200.single_store.standard.yml", there is a "basic_holding_cost". should I set it to 0.003 when I want to repeat exp in Figure 3(IPPO sku200)?

**Comment by VictorYXL** [comment]
Apologies for the delayed response regarding my GitHub account complications. In practice, the calculation of holding_cost is more nuanced than what is outlined in the documentation. It incorporates the product's volume into the equation. The holding_cost is computed as follows: holding_cost = basic_holding_cost + (unit_storage_cost * volume), where the basic_holding_cost is set at 0.001 and the unit_storage_cost at 0.002. This formula allows us to address more intricate scenarios.

**Comment by BackMountainDevil** [comment]
Thank you for you kindly explaination. That config is helpful to reproduce your baseline
